// Generated by typings
// Source: https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/56295f5058cac7ae458540423c50ac2dcf9fc711/memory-cache/memory-cache.d.ts
declare module "memory-cache" {
	export function put(key: any, value: any, time?: number, timeoutCallback?: (key: any) => void): void;
	export function get(key: any): any;
	export function del(key: any): void;
	export function clear(): void;

	export function size(): number;
	export function memsize(): number;

	export function debug(bool: boolean): void;
	export function hits(): number;
	export function misses(): number;
	export function keys() : any;
}
